server:
  port: ${PORT:8081}

my:
  docker:
    username: ${DOCKER_USERNAME}
    image: ${IMAGE_NAME}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/antmen?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
          default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update   # 옵션: none, validate, update, create, create-drop
    show-sql: true       # 콘솔에 SQL 출력