server:
  port: ${PORT:8080}

my:
  docker:
    username: ${DOCKER_USERNAME}
    image: ${IMAGE_NAME}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/antWork?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: antMen    # 환경변수 사용 가능, 기본값은 root
    password: "!dkdlxl1234" # 환경변수 사용 가능, 기본값은 password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: update   # 옵션: none, validate, update, create, create-drop
    show-sql: true       # 콘솔에 SQL 출력
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect