name: "CI/CD: Build & Deploy to EC2"

on:
  push:
    # types: [closed] 
    branches: [fix/#22-github-action]

jobs:
  build:
    # if: github.event.pull_request.merged == true
    name: 🛠 Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate .env from Secrets
        run: |
          cat <<EOF > .env
          PORT=${{ secrets.ENV_PORT }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME=${{ secrets.ENV_IMAGE_NAME }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
          SPRING_DATABASE_URL=${{ secrets.SPRING_DATABASE_URL }}
          EOF

      - name: Run build.sh
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
          echo "=== Application Container Logs ==="
          docker logs ${{ secrets.ENV_IMAGE_NAME }} || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/antmen:latest

  deploy:
    name: 🚀 Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear server folder before upload
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo rm -rf ~/apps/server
            mkdir -p ~/apps/server
            sudo chown -R $USER:$USER ~/apps/server

      - name: Copy docker-compose.yml, nginx
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "docker-compose.yml,nginx/nginx.conf,nginx/default.conf"
          target: ~/apps/server

      - name: SSH into EC2 and restart container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/apps/server
            export PORT=${{ secrets.ENV_PORT }}
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export IMAGE_NAME=${{ secrets.ENV_IMAGE_NAME }}
            export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            export MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export MYSQL_PORT=${{ secrets.MYSQL_PORT }}
            export MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
            export SPRING_DATABASE_URL=${{ secrets.SPRING_DATABASE_URL }}
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            docker compose pull
            docker compose down
            docker compose up -d

