name: "CI/CD: Build & Deploy to EC2"

on:
  push:
    branches: [feature/CICD-#1]

jobs:
  build:
    name: 🛠 Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate .env from Secrets
        run: |
          cat <<EOF > .env
          PORT=${{ secrets.ENV_PORT }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME=${{ secrets.ENV_IMAGE_NAME }}
          EOF

      - name: Run build.sh
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/antmen:latest

  deploy:
    name: 🚀 Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure files exist before SCP
        run: |
          ls -al ./docker-compose.yml
          ls -al ./nginx/nginx.conf
          ls -al ./nginx/default.conf

      - name: Copy docker-compose.yml, nginx
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "docker-compose.yml,nginx/nginx.conf,nginx/default.conf"
          target: ~/apps/server
          overwrite: true

      - name: SSH into EC2 and restart container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/apps/server
            export PORT=${{ secrets.ENV_PORT }}
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export IMAGE_NAME=${{ secrets.ENV_IMAGE_NAME }}
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            docker compose pull
            docker compose down
            docker compose up -d

